[project]
name = "covid-cities"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
"humanize",
"pandas",
"plotly",
"streamlit",
"protobuf"]
